// Copyright (C) 2026 Zhongtai Virtual
//
// This file is part of MumbledFlight.
//
// MumbledFlight is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// MumbledFlight is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with MumbledFlight.  If not, see <https://www.gnu.org/licenses/>.


//! MumbledFlight: A high-fidelity bridge between X-Plane 12 and Mumble.

mod xplane;

use anyhow::Result;
use clap::{Parser, ValueEnum};
use log::{error, info};
use mumbled_flight_core::config::Config;
use mumbled_flight_core::mumble::{self, voip::xplane_to_mumble, InputType, MumbleStackConfig, TestClient};
use mumbled_flight_core::state::CockpitState;
use std::net::SocketAddr;
use std::path::PathBuf;
use std::sync::{Arc, Mutex};

#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
enum CliClient {
    Voice,
    Ic,
    Pa,
    Radio,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum, Default)]
enum CliZone {
    Fbo,
    #[default]
    Aircraft,
}

impl From<CliZone> for mumbled_flight_core::state::SharedCockpitZone {
    fn from(z: CliZone) -> Self {
        match z {
            CliZone::Fbo => Self::InFbo,
            CliZone::Aircraft => Self::AroundOrInAircraft,
        }
    }
}

#[derive(Parser, Debug)]
#[command(
    author = "MumbledFlight Team",
    version,
    about = "High-fidelity shared cockpit audio bridge for X-Plane 12 and Mumble.",
    long_about = "A standalone utility that bridges X-Plane 12 cockpit states with Mumble VoIP."
)]
struct Args {
    /// The Flight ID or Session Name. Partners must use the same ID to meet.
    #[arg(index = 1)]
    flight_id: Option<String>,

    /// Path to X-Plane 12 root folder. Used to extract your pilot name automatically.
    #[arg(short, long, value_name = "PATH")]
    xplane_path: Option<PathBuf>,

    /// Microphone gain multiplier. Acts as a pre-amp before filtering. (e.g. 1.5)
    #[arg(short, long, default_value_t = 1.0, value_name = "FACTOR")]
    gain: f32,

    /// Custom username prefix. (Required if --xplane-path is missing).
    #[arg(short, long, value_name = "NAME")]
    user: Option<String>,

    /// Enable RNNoise noise suppression on the microphone input.
    #[arg(short, long, default_value_t = false)]
    denoise: bool,

    /// Microphone input device name (PipeWire node name on Linux). Defaults to system default.
    #[arg(long, value_name = "DEVICE")]
    mic_device: Option<String>,

    /// Loopback device for X-Pilot radio audio.
    #[arg(short, long, value_name = "DEVICE")]
    radio_source: Option<String>,

    /// Linux only: Automatically create a virtual 'MumblingRadio' loopback device.
    #[arg(long, default_value_t = false)]
    auto_sink: bool,

    /// Mumble server address (host:port).
    #[arg(short, long, default_value = "127.0.0.1:64738", value_name = "HOST:PORT")]
    server: String,

    /// Mumble server password, if the server requires one.
    #[arg(short = 'P', long, value_name = "PASSWORD")]
    password: Option<String>,

    /// Client certificate (PKCS#12 / .p12) used as the TLS identity instead of password auth.
    #[arg(long, value_name = "FILE")]
    client_cert: Option<PathBuf>,

    /// Passphrase for the --client-cert file, if it is protected.
    #[arg(long, value_name = "PASSPHRASE")]
    cert_pass: Option<String>,

    /// Verify the server's certificate against this CA or pinned cert (PEM/DER). Without it the
    /// server certificate is not verified.
    #[arg(long, value_name = "FILE")]
    server_ca: Option<PathBuf>,

    /// List all available audio input and output devices on your system.
    #[arg(long, default_value_t = false)]
    list_devices: bool,

    /// Test: spawn only a single client type. Omit to run all clients.
    /// Use without a value to default to voice.
    #[arg(long, value_name = "TYPE", num_args = 0..=1, default_missing_value = "voice")]
    test: Option<CliClient>,

    /// Zone the ambient client starts in. Only meaningful with --client ambient.
    /// Use without a value to default to aircraft.
    #[arg(long, value_name = "ZONE", num_args = 0..=1, default_missing_value = "aircraft")]
    zone: Option<CliZone>,

    /// Transmit from a fixed position given in X-Plane coordinates (X,Y,Z meters).
    /// Use without a value for the origin (0,0,0), or supply coordinates: --pos 2,0,-6.8
    #[arg(long, value_name = "X,Y,Z", num_args = 0..=1, default_missing_value = "0,0,0")]
    pos: Option<String>,

    /// Debug: replace microphone with a 500 Hz sine tone generated by ffmpeg.
    #[arg(long, default_value_t = false, conflicts_with = "file")]
    sine: bool,

    /// Debug: replace microphone with an audio file decoded by ffmpeg (loops on EOF).
    #[arg(long, value_name = "PATH", conflicts_with = "sine")]
    file: Option<PathBuf>,
}

#[tokio::main]
async fn main() -> Result<()> {
    env_logger::init();
    eprintln!("MumbledFlight  Copyright (C) 2026 Zhongtai Virtual");
    eprintln!("This program comes with ABSOLUTELY NO WARRANTY.");
    eprintln!("This is free software, and you are welcome to redistribute it");
    eprintln!("under certain conditions; see the LICENSE file for details.");
    let args = Args::parse();

    // 1. Device Discovery Mode
    if args.list_devices {
        mumble::audio::list_audio_devices();
        return Ok(());
    }

    // Ensure we have a flight ID for normal operation
    let flight_id = args
        .flight_id
        .expect("Error: Flight ID is required. Use --help for usage details.");

    info!("MumbledFlight Standalone Bridge starting...");

    // 2. Initialize shared state
    let state = Arc::new(Mutex::new(CockpitState::default()));
    let server_addr: SocketAddr = args.server.parse()?;

    // 3. Resolve Identity
    let user_prefix = if let Some(u) = args.user {
        u
    } else if let Some(ref path) = args.xplane_path {
        let cfg = Config::read_cl60_config(path)
            .expect("Critical: Found X-Plane path but could not read CL650 configuration.");
        cfg.user_name
    } else {
        error!("Username could not be determined.");
        error!("Please provide either --user <Name> or --xplane-path <Path>.");
        std::process::exit(1);
    };

    info!(
        "Session ready — user: {}, flight: {}, denoise: {}",
        user_prefix, flight_id, args.denoise
    );

    // 4. Start Mumble Stack
    let test_pos: Option<[f32; 3]> = args.pos.map(|s| {
        let p: Vec<f32> = s
            .split(',')
            .map(|c| c.trim().parse().unwrap_or(0.0))
            .collect();
        xplane_to_mumble([
            p.first().copied().unwrap_or(0.0),
            p.get(1).copied().unwrap_or(0.0),
            p.get(2).copied().unwrap_or(0.0),
        ])
    });
    // Pre-configure state for single-client test mode — DataRef bridge is skipped below.
    if args.test.is_some() {
        use mumbled_flight_core::state::{AcpMicSelection, SharedCockpitRole};
        let mut s = state.lock().unwrap();
        s.role = SharedCockpitRole::Pilot;
        s.zone = args.zone.unwrap_or_default().into();
        match args.test {
            Some(CliClient::Ic) => {
                s.acp_ic = true;
            }
            Some(CliClient::Pa) => {
                s.mic = AcpMicSelection::Pa;
                s.acp_rt = true;
            }
            Some(CliClient::Radio) => {
                s.com1_rx = true;
                s.spkr_tog = true;
            }
            _ => {}
        }
    }
    // Load the optional client certificate up front so a bad path/passphrase aborts cleanly.
    let client_cert = match &args.client_cert {
        Some(path) => Some(Arc::new(mumble::ClientCert::load(
            path,
            args.cert_pass.as_deref().unwrap_or(""),
        )?)),
        None => None,
    };
    let server_trust = match &args.server_ca {
        Some(path) => Some(Arc::new(mumble::ServerTrust::load(path)?)),
        None => None,
    };

    let state_mumble = Arc::clone(&state);
    tokio::spawn(async move {
        use std::sync::atomic::{AtomicBool, AtomicU32};
        let test_client = match args.test {
            None                    => TestClient::All,
            Some(CliClient::Voice)  => TestClient::Voice,
            Some(CliClient::Ic)     => TestClient::Ic,
            Some(CliClient::Pa)     => TestClient::Pa,
            Some(CliClient::Radio)  => TestClient::Radio,
        };
        let statuses = std::sync::Arc::new(std::sync::Mutex::new(std::collections::HashMap::new()));
        let input_type = if let Some(path) = args.file {
            InputType::File(path)
        } else if args.sine {
            InputType::Sine
        } else {
            InputType::Real
        };
        mumble::run_mumble_stack(MumbleStackConfig {
            state: state_mumble,
            user_name: user_prefix,
            session_id: flight_id,
            server_password: args.password.unwrap_or_default(),
            client_cert,
            server_trust,
            mic_gain: Arc::new(AtomicU32::new(args.gain.to_bits())),
            denoise: args.denoise,
            radio_source: args.radio_source,
            auto_sink: args.auto_sink,
            test_client,
            input_type,
            mic_device: args.mic_device,
            test_pos, // None = use real X-Plane position; Some = fixed pos
            server_addr,
            ambient_output: None,
            ic_output: None,
            ambient_vol: Arc::new(AtomicU32::new(1.0_f32.to_bits())),
            ic_vol:      Arc::new(AtomicU32::new(1.0_f32.to_bits())),
            statuses,
            // One-shot process — never torn down, so the flag is never set.
            shutdown: Arc::new(AtomicBool::new(false)),
            spatial_width: Arc::new(AtomicU32::new(1.0_f32.to_bits())),
        })
        .await;
    });

    // 5. Run the X-Plane WebAPI bridge (Main Thread) — skipped in single-client test mode
    //    to prevent DataRef updates from overwriting the pre-configured state above.
    if args.test.is_none() {
        xplane::bridge::run_bridge_forever(state).await?;
    } else {
        std::future::pending::<()>().await;
    }
    Ok(())
}
