//! MumbledFlight: A high-fidelity bridge between X-Plane 12 and Mumble.

mod xplane;

use anyhow::Result;
use clap::{Parser, ValueEnum};
use log::{error, info};
use mumbled_flight_core::config::Config;
use mumbled_flight_core::mumble::{self, voip::xplane_to_mumble, InputType, MumbleStackConfig, TestClient};
use mumbled_flight_core::state::CockpitState;
use std::net::SocketAddr;
use std::path::PathBuf;
use std::sync::{Arc, Mutex};

#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
enum CliClient {
    Voice,
    Ic,
    Pa,
    Radio,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
enum CliZone {
    Fbo,
    Aircraft,
}

#[derive(Parser, Debug)]
#[command(
    author = "MumbledFlight Team",
    version,
    about = "High-fidelity shared cockpit audio bridge for X-Plane 12 and Mumble.",
    long_about = "A standalone utility that bridges X-Plane 12 cockpit states with Mumble VoIP."
)]
struct Args {
    /// The Flight ID or Session Name. Partners must use the same ID to meet.
    #[arg(index = 1)]
    flight_id: Option<String>,

    /// Path to X-Plane 12 root folder. Used to extract your pilot name automatically.
    #[arg(short, long, value_name = "PATH")]
    xplane_path: Option<PathBuf>,

    /// Microphone gain multiplier. Acts as a pre-amp before filtering. (e.g. 1.5)
    #[arg(short, long, default_value_t = 1.0, value_name = "FACTOR")]
    gain: f32,

    /// Custom username prefix. (Required if --xplane-path is missing).
    #[arg(short, long, value_name = "NAME")]
    user: Option<String>,

    /// Enable RNNoise noise suppression on the microphone input.
    #[arg(short, long, default_value_t = false)]
    denoise: bool,

    /// Microphone input device name (PipeWire node name on Linux). Defaults to system default.
    #[arg(long, value_name = "DEVICE")]
    mic_device: Option<String>,

    /// Loopback device for X-Pilot radio audio.
    #[arg(short, long, value_name = "DEVICE")]
    radio_source: Option<String>,

    /// Linux only: Automatically create a virtual 'MumblingRadio' loopback device.
    #[arg(long, default_value_t = false)]
    auto_sink: bool,

    /// Mumble server address (host:port).
    #[arg(short, long, default_value = "127.0.0.1:64738", value_name = "HOST:PORT")]
    server: String,

    /// List all available audio input and output devices on your system.
    #[arg(long, default_value_t = false)]
    list_devices: bool,

    /// Test: spawn only a single client type. Omit to run all clients.
    /// Use without a value to default to voice.
    #[arg(long, value_name = "TYPE", num_args = 0..=1, default_missing_value = "voice")]
    test: Option<CliClient>,

    /// Zone the ambient client starts in. Only meaningful with --client ambient.
    /// Use without a value to default to aircraft.
    #[arg(long, value_name = "ZONE", num_args = 0..=1, default_missing_value = "aircraft")]
    zone: Option<CliZone>,

    /// Transmit from a fixed position given in X-Plane coordinates (X,Y,Z meters).
    /// Use without a value for the origin (0,0,0), or supply coordinates: --pos 2,0,-6.8
    #[arg(long, value_name = "X,Y,Z", num_args = 0..=1, default_missing_value = "0,0,0")]
    pos: Option<String>,

    /// Debug: replace microphone with a 500 Hz sine tone generated by ffmpeg.
    #[arg(long, default_value_t = false, conflicts_with = "file")]
    sine: bool,

    /// Debug: replace microphone with an audio file decoded by ffmpeg (loops on EOF).
    #[arg(long, value_name = "PATH", conflicts_with = "sine")]
    file: Option<PathBuf>,
}

#[tokio::main]
async fn main() -> Result<()> {
    env_logger::init();
    let args = Args::parse();

    // 1. Device Discovery Mode
    if args.list_devices {
        mumble::audio::list_audio_devices();
        return Ok(());
    }

    // Ensure we have a flight ID for normal operation
    let flight_id = args
        .flight_id
        .expect("Error: Flight ID is required. Use --help for usage details.");

    info!("MumbledFlight Standalone Bridge starting...");

    // 2. Initialize shared state
    let state = Arc::new(Mutex::new(CockpitState::default()));
    let server_addr: SocketAddr = args.server.parse()?;

    // 3. Resolve Identity
    let user_prefix = if let Some(u) = args.user {
        u
    } else if let Some(ref path) = args.xplane_path {
        let cfg = Config::read_cl60_config(path)
            .expect("Critical: Found X-Plane path but could not read CL650 configuration.");
        cfg.user_name
    } else {
        error!("Username could not be determined.");
        error!("Please provide either --user <Name> or --xplane-path <Path>.");
        std::process::exit(1);
    };

    info!(
        "Session ready — user: {}, flight: {}, denoise: {}",
        user_prefix, flight_id, args.denoise
    );

    // 4. Start Mumble Stack
    let test_pos: Option<[f32; 3]> = args.pos.map(|s| {
        let p: Vec<f32> = s
            .split(',')
            .map(|c| c.trim().parse().unwrap_or(0.0))
            .collect();
        xplane_to_mumble([
            p.first().copied().unwrap_or(0.0),
            p.get(1).copied().unwrap_or(0.0),
            p.get(2).copied().unwrap_or(0.0),
        ])
    });
    // Pre-configure state for single-client test mode — DataRef bridge is skipped below.
    if args.test.is_some() {
        use mumbled_flight_core::state::{AcpMicSelection, SharedCockpitRole, SharedCockpitZone};
        let mut s = state.lock().unwrap();
        s.role = SharedCockpitRole::Pilot;
        if let Some(zone) = args.zone {
            s.zone = match zone {
                CliZone::Fbo => SharedCockpitZone::InFbo,
                CliZone::Aircraft => SharedCockpitZone::AroundOrInAircraft,
            };
        }
        match args.test {
            Some(CliClient::Ic) => {
                s.acp_ic = true;
            }
            Some(CliClient::Pa) => {
                s.mic = AcpMicSelection::Pa;
                s.acp_rt = true;
            }
            Some(CliClient::Radio) => {
                s.com1_rx = true;
                s.spkr_tog = true;
            }
            _ => {}
        }
    }
    let state_mumble = Arc::clone(&state);
    tokio::spawn(async move {
        use std::sync::atomic::{AtomicBool, AtomicU32};
        let test_client = match args.test {
            None                    => TestClient::All,
            Some(CliClient::Voice)  => TestClient::Voice,
            Some(CliClient::Ic)     => TestClient::Ic,
            Some(CliClient::Pa)     => TestClient::Pa,
            Some(CliClient::Radio)  => TestClient::Radio,
        };
        let statuses = std::sync::Arc::new(std::sync::Mutex::new(std::collections::HashMap::new()));
        let input_type = if let Some(path) = args.file {
            InputType::File(path)
        } else if args.sine {
            InputType::Sine
        } else {
            InputType::Real
        };
        mumble::run_mumble_stack(MumbleStackConfig {
            state: state_mumble,
            user_name: user_prefix,
            session_id: flight_id,
            mic_gain: Arc::new(AtomicU32::new(args.gain.to_bits())),
            denoise: args.denoise,
            radio_source: args.radio_source,
            auto_sink: args.auto_sink,
            test_client,
            input_type,
            mic_device: args.mic_device,
            test_pos, // None = use real X-Plane position; Some = fixed pos
            server_addr,
            ambient_output: None,
            ic_output: None,
            ambient_vol: Arc::new(AtomicU32::new(1.0_f32.to_bits())),
            ic_vol:      Arc::new(AtomicU32::new(1.0_f32.to_bits())),
            statuses,
            // One-shot process — never torn down, so the flag is never set.
            shutdown: Arc::new(AtomicBool::new(false)),
        })
        .await;
    });

    // 5. Run the X-Plane WebAPI bridge (Main Thread) — skipped in single-client test mode
    //    to prevent DataRef updates from overwriting the pre-configured state above.
    if args.test.is_none() {
        xplane::bridge::run_bridge_forever(state).await?;
    } else {
        std::future::pending::<()>().await;
    }
    Ok(())
}
