// Copyright (C) 2026 Zhongtai Virtual
//
// This file is part of MumbledFlight.
//
// MumbledFlight is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// MumbledFlight is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with MumbledFlight.  If not, see <https://www.gnu.org/licenses/>.

//! Mumble VoIP stack — public types and entry point.

pub mod audio;
mod stack;
pub mod voip;

pub use self::voip::client::VoipClientStatus as ClientStatus;
pub use self::voip::client::{ClientCert, ServerTrust, VoipClientStatus};
pub use stack::run_mumble_stack;

use std::collections::HashMap;
use std::sync::atomic::{AtomicBool, AtomicU32};
use std::sync::{Arc, Mutex};

use crate::state::CockpitState;

/// Number of PCM samples per Opus frame at 48 kHz (20 ms).
pub const OPUS_FRAME_SAMPLES: usize = 960;

/// Maps a display label (e.g. "Voice", "IC") to that client's live connection status.
pub type VoipStatuses = Arc<Mutex<HashMap<String, Arc<Mutex<VoipClientStatus>>>>>;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum VoipClient {
    #[default]
    All,
    Voice,
    Ic,
    Pa,
    Radio,
}

/// Microphone source for the VoIP stack.
#[derive(Debug, Default)]
pub enum InputType {
    /// Real microphone capture via CPAL.
    #[default]
    Real,
    /// 500 Hz sine tone generated by ffmpeg (test only).
    Sine,
    /// Audio file decoded by ffmpeg, looping on EOF (test only).
    File(std::path::PathBuf),
}

/// Audio source for the radio relay client.
#[derive(Debug, Default)]
pub enum RadioSource {
    /// Radio relay disabled — the Radio VoIP client is not spawned.
    #[default]
    Disabled,
    /// Auto-create a "MumblingRadio" virtual null-sink (Linux/PipeWire only).
    #[cfg(target_os = "linux")]
    AutoSink,
    /// Capture from a named input device / PipeWire node.
    Device(String),
}

/// Everything `run_mumble_stack` needs to bring up the VoIP stack. Built by each frontend
/// (CLI / plugin) from its own config + cockpit state.
pub struct MumbleStackConfig {
    pub state: Arc<Mutex<CockpitState>>,
    pub user_name: String,
    pub session_id: String,
    /// Mumble server password (empty = none). Shared by all four clients on connect.
    pub server_password: String,
    /// Optional client certificate for TLS identity (alternative to password auth).
    pub client_cert: Option<Arc<ClientCert>>,
    /// Optional trust anchor(s) to verify the server certificate (server cert or its CA).
    pub server_trust: Option<Arc<ServerTrust>>,
    pub mic_gain: Arc<AtomicU32>,
    pub denoise: bool,
    pub radio_source: RadioSource,
    pub voip_client: VoipClient,
    pub input_type: InputType,
    /// PipeWire/CPAL node name to use for microphone capture. `None` = system default.
    pub mic_device: Option<String>,
    pub test_pos: Option<[f32; 3]>,
    pub server_host: String,
    pub server_port: u16,
    pub ambient_output: Option<String>,
    pub ic_output: Option<String>,
    pub ambient_vol: Arc<AtomicU32>,
    pub ic_vol: Arc<AtomicU32>,
    pub statuses: VoipStatuses,
    /// Set to `true` by the frontend when the connection is torn down. The microphone capture
    /// stream watches this and exits, dropping its CPAL/PipeWire stream instead of leaking it
    /// across reconnects. CLI (one-shot) can pass a flag that is never set.
    pub shutdown: Arc<AtomicBool>,
    /// Stereo width for spatialized playback: 0.0 = mono, 1.0 = full spatial. Live-adjustable.
    pub spatial_width: Arc<AtomicU32>,
}
