//! Orchestrates the Mumble VoIP stack with multi-source Radio Relay.

pub mod audio;
pub mod voip;

use self::audio::{create_linux_sink, start_capture, start_loopback_capture, start_playback};
use self::voip::client::{ClientRole, MumbleVoipClient, VoipClientStatus};
use crate::state::{CockpitState, SharedCockpitZone};
use std::collections::HashMap;
use std::net::SocketAddr;
use std::sync::atomic::AtomicU32;
use std::sync::{Arc, Mutex, OnceLock};
use tokio::sync::{broadcast, mpsc};

pub use self::voip::client::VoipClientStatus as ClientStatus;

/// Maps a display label (e.g. "Voice", "IC") to that client's live connection status.
pub type VoipStatuses = Arc<Mutex<HashMap<String, Arc<Mutex<VoipClientStatus>>>>>;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum TestClient {
    #[default]
    All,
    Voice,
    Ic,
    Pa,
    Radio,
}

/// Microphone source for the VoIP stack.
#[derive(Debug, Default)]
pub enum MicSource {
    /// Real microphone capture via CPAL.
    #[default]
    Real,
    /// 500 Hz sine tone generated by ffmpeg (test only).
    Sine,
    /// Audio file decoded by ffmpeg, looping on EOF (test only).
    File(std::path::PathBuf),
}

/// Everything `run_mumble_stack` needs to bring up the VoIP stack. Built by each frontend
/// (CLI / plugin) from its own config + cockpit state.
pub struct MumbleStackConfig {
    pub state: Arc<Mutex<CockpitState>>,
    pub user_name: String,
    pub session_id: String,
    pub mic_gain: Arc<AtomicU32>,
    pub denoise: bool,
    pub radio_source: Option<String>,
    pub auto_sink: bool,
    pub test_client: TestClient,
    pub mic_source: MicSource,
    pub test_pos: Option<[f32; 3]>,
    pub server_addr: SocketAddr,
    pub ambient_output: Option<String>,
    pub ic_output: Option<String>,
    pub statuses: VoipStatuses,
}

/// Spawns a single Mumble client's run loop, logging a disconnect at error level.
/// `client` carries the static per-role config; the rest is the per-connection wiring.
fn spawn_client(
    client: MumbleVoipClient,
    server_addr: SocketAddr,
    state: Arc<Mutex<CockpitState>>,
    audio_rx: broadcast::Receiver<Vec<f32>>,
    playback_tx: mpsc::Sender<Vec<f32>>,
) {
    tokio::spawn(async move {
        if let Err(e) = client.run(server_addr, state, audio_rx, playback_tx).await {
            log::error!("[VoIP:{}] disconnected: {e}", client.username);
        }
    });
}

pub async fn run_mumble_stack(cfg: MumbleStackConfig) {
    let MumbleStackConfig {
        state,
        user_name,
        session_id,
        mic_gain,
        denoise,
        radio_source,
        auto_sink,
        test_client,
        mic_source,
        test_pos,
        server_addr,
        ambient_output,
        ic_output,
        statuses,
    } = cfg;

    // 1. MIC Chain
    let (mic_tx, _) = broadcast::channel::<Vec<f32>>(128);
    let mic_tx_clone = mic_tx.clone();
    let d_mic = denoise;
    std::thread::spawn(move || {
        let (sync_tx, mut sync_rx) = mpsc::channel(128);
        match mic_source {
            MicSource::Sine          => audio::start_sine_capture(sync_tx, mic_gain),
            MicSource::File(path)    => audio::start_file_capture(path, sync_tx, mic_gain),
            MicSource::Real          => start_capture(sync_tx, d_mic, mic_gain, 0.0, None),
        }
        while let Some(frame) = sync_rx.blocking_recv() {
            let _ = mic_tx_clone.send(frame);
        }
    });

    // Wait for the primary mic capture to fully establish itself in the OS mixer
    tokio::time::sleep(std::time::Duration::from_secs(2)).await;

    // 2. RADIO Chain
    let final_radio_source = if auto_sink {
        create_linux_sink()
    } else {
        radio_source
    };

    let radio_tx = match final_radio_source {
        Some(src) if matches!(test_client, TestClient::All | TestClient::Radio) => {
            Some(radio_loopback_sender(src))
        }
        _ => None,
    };

    // 3. Playback Mixers — ambient and IC each route to their own output device.
    //    Radio received audio shares the ambient mixer (no separate radio output).
    let (ambient_pb_tx, ambient_pb_rx) = mpsc::channel(1024);
    let (ic_pb_tx, ic_pb_rx) = mpsc::channel(1024);
    let ic_monitor_tx = ic_pb_tx.clone();
    start_playback(ambient_pb_rx, ambient_output);
    start_playback(ic_pb_rx, ic_output);

    // Helper: allocate a status slot and register it in the shared map.
    let mk_status = |label: &str| -> Arc<Mutex<VoipClientStatus>> {
        let slot = Arc::new(Mutex::new(VoipClientStatus::Connecting));
        statuses
            .lock()
            .unwrap()
            .insert(label.to_string(), Arc::clone(&slot));
        slot
    };

    let fbo_ch = format!("{session_id}_ambient_fbo");
    let aircraft_ch = format!("{session_id}_ambient_aircraft");
    let ambient_ctx = format!("{session_id}_ambient");

    // 4. Voice Client (natural speech, spatialised). Starts in the channel for the current zone.
    if matches!(test_client, TestClient::All | TestClient::Voice) {
        let initial_ambient_ch = match state.lock().unwrap().zone {
            SharedCockpitZone::InFbo => fbo_ch.clone(),
            SharedCockpitZone::AroundOrInAircraft => aircraft_ch.clone(),
        };
        spawn_client(
            MumbleVoipClient {
                username: format!("{user_name}_voice"),
                context: ambient_ctx.clone(),
                role: ClientRole::Voice,
                voip_status: mk_status("Voice"),
                target_channel: initial_ambient_ch,
                zone_channels: Some((fbo_ch.clone(), aircraft_ch.clone())),
                test_pos,
            },
            server_addr,
            Arc::clone(&state),
            mic_tx.subscribe(),
            ambient_pb_tx.clone(),
        );
    }

    if test_client == TestClient::Voice {
        return;
    }

    // 5. Intercom Client
    if !matches!(test_client, TestClient::Pa | TestClient::Radio) {
        spawn_client(
            MumbleVoipClient {
                username: format!("{user_name}_ic"),
                context: format!("{session_id}_ic"),
                role: ClientRole::Ic,
                voip_status: mk_status("IC"),
                target_channel: format!("{session_id}_ic"),
                zone_channels: None,
                test_pos,
            },
            server_addr,
            Arc::clone(&state),
            mic_tx.subscribe(),
            ic_pb_tx,
        );
    }

    // 6. PA (Public Address) Client — always in aircraft channel
    // TODO: PA is broadcast from multiple speakers (PSUs above each seat, lavatory ceiling).
    //       A single fixed point source does not accurately simulate this. Consider rendering
    //       PA as a non-positional flat mix, or blending several source positions, to replicate
    //       the enveloping "speakers everywhere" effect. Door attenuation should also be
    //       bypassed since the speakers are inside the fuselage.
    const PA_POSITION: [f32; 3] = [0.0, 0.0, 0.0]; // placeholder until rendering is redesigned
    if !matches!(test_client, TestClient::Ic | TestClient::Radio) {
        spawn_client(
            MumbleVoipClient {
                username: format!("{user_name}_PA"),
                context: ambient_ctx.clone(),
                role: ClientRole::Pa,
                voip_status: mk_status("PA"),
                target_channel: aircraft_ch.clone(),
                zone_channels: None,
                test_pos: Some(PA_POSITION),
            },
            server_addr,
            Arc::clone(&state),
            mic_tx.subscribe(),
            ambient_pb_tx.clone(),
        );
    }

    // 7. Radio Relay Client + local COM monitor
    // (radio_tx is a cloned Sender into the shared loopback channel — no new PW stream)
    if let Some(rtx) = radio_tx {
        // X-Plane cockpit-speaker position; converted to Mumble's Z convention.
        const RADIO_SPEAKER_POSITION: [f32; 3] = voip::xplane_to_mumble([0.0, 0.9, -6.8]);
        spawn_client(
            MumbleVoipClient {
                username: format!("{user_name}_radio"),
                context: ambient_ctx.clone(),
                role: ClientRole::Radio { has_source: true },
                voip_status: mk_status("Radio"),
                target_channel: aircraft_ch.clone(),
                zone_channels: None,
                test_pos: test_pos.or(Some(RADIO_SPEAKER_POSITION)),
            },
            server_addr,
            Arc::clone(&state),
            rtx.subscribe(),
            ambient_pb_tx.clone(),
        );

        // Always mirror the radio source to the IC output device so pilots hear
        // COM audio through their designated IC headphone output.
        // TX gating (com1_rx / com2_rx) is handled separately in on_mic_pcm.
        let mut monitor_rx = rtx.subscribe();
        tokio::spawn(async move {
            loop {
                match monitor_rx.recv().await {
                    Ok(pcm) => {
                        let stereo: Vec<f32> = pcm.iter().flat_map(|&s| [s, s]).collect();
                        let _ = ic_monitor_tx.send(stereo).await;
                    }
                    Err(broadcast::error::RecvError::Lagged(_)) => continue,
                    Err(broadcast::error::RecvError::Closed) => break,
                }
            }
        });
    }
}

/// Returns a `Sender` into the shared radio loopback broadcast channel.
/// The underlying PipeWire capture stream and forwarding thread are created only once
/// per process regardless of how many times `run_mumble_stack` is called.
fn radio_loopback_sender(source_name: String) -> broadcast::Sender<Vec<f32>> {
    static TX: OnceLock<broadcast::Sender<Vec<f32>>> = OnceLock::new();
    TX.get_or_init(|| {
        let (tx, _) = broadcast::channel::<Vec<f32>>(128);
        let tx_fwd = tx.clone();
        std::thread::spawn(move || {
            let (sync_tx, mut sync_rx) = mpsc::channel(128);
            start_loopback_capture(source_name, sync_tx);
            while let Some(frame) = sync_rx.blocking_recv() {
                let _ = tx_fwd.send(frame);
            }
        });
        tx
    })
    .clone()
}
